Add show-splash to configure hook

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -131,3 +131,23 @@ fi
 if [ $(($config_changes+$display_changes)) -gt 0 ]; then
   snapctl restart $SNAP_NAME
 fi
+
+# show-splash 
+show-splash=$(snapctl get show-splash)
+if [ -n "${show-splash}" ]; then
+  if [[ ! "${show-splash}" =~ ^(true|false)$ ]]; then
+    echo "ERROR: '$show-splash' is not a valid cursor option (true|false)"
+    exit 1
+  fi
+
+  if [ "show-splash=${show-splash}" != "$(grep show-splash= ${miral_kiosk_config})" ]; then
+    if [ $config_changes -gt 0 ]; then
+      sed '/^show-splash/d' ${miral_kiosk_config}
+    else
+      sed --in-place=.save '/^show-splash/d' ${miral_kiosk_config}
+    fi
+    echo show-splash=${show-splash} >> ${miral_kiosk_config}
+    let config_changes+=1
+  fi
+fi
+
